info:
    version: @pom.version@
    stage: dev
server:
    port: 8083

management: 
    security: 
        enabled: false
idle:
    url:
        heroType:
            http://localhost:8082/heroType
        hero:
            http://localhost:8082/hero
        battleHero:
            http://localhost:8081/battleHero
        formation:
            http://localhost:8081/formation
    config:
        # RabbitMQ Settings
        rabbitmq:
            hostname: 172.16.50.24
            username: admin
            password: admin123
            
        # Mongo Settings
        mongodb:
            hostname: localhost
            port: 11111
            database: test
        
        chat:
            #Redis
            redis:
                hostname: 172.16.50.24
                port: 6379
            relay:
                hostname: localhost
                port: 61613
                username: admin
                password: admin123

keycloak:
    auth-server-url: http://localhost:8180/auth
    realm: idlerealm
    resource: idlegame
    public-client: true

#Spring Boot Config            
spring:
    profiles:
        active: default
    application:
        name: @pom.artifactId@
    jackson:
        default-property-inclusion: non_null