server:
    port: ${PORT:8888}
    compression:
        enabled: true
spring:
    cloud:
        config:
            server:
                git:
                    uri: ${GITURI:https://github.com/rfaita/idlegamerepository.git}