package com.idle.game.core.type;

/**
 *
 * @author rafael
 */
public enum TargetType {

    SELF,
    FRONT_LINE, FRONT_LINE_NO_SELF,
    MIDDLE_LINE, MIDDLE_LINE_NO_SELF,
    BACK_LINE, BACK_LINE_NO_SELF,
    RANDOM, TWO_RANDOM, THREE_RANDOM, FOUR_RANDOM,
    RANDOM_NO_SELF,
    NO_FRONT_LINE,
    IN_FRONT, IN_FRONT_PILLAR, IN_FRONT_SMALL_PILLAR,
    LOWER_LIFE, BIGGER_LIFE,
    ALL, ALL_FRONT_LINE, ALL_MIDDLE_LINE, ALL_BACK_LINE,
    DEAD,
    RANDOM_ADJACENT;
}
