info:
    version: @pom.version@
    stage: dev
server:
    port: 9000

management: 
    security: 
        enabled: false
zuul:
  prefix: /idle/api
  routes:
    friend:
        path: /friend/**
        sensitiveHeaders:
        url: http://localhost:8085/friend
    actionEffectTypes:
        path: /actionEffectTypes/**
        sensitiveHeaders:
        url: http://localhost:8082/actionEffectTypes
    heroTypes:
        path: /heroTypes/**
        sensitiveHeaders:
        url: http://localhost:8082/heroTypes
    heroTypeTypes:
        path: /heroTypeTypes/**
        sensitiveHeaders:
        url: http://localhost:8082/heroTypeTypes
    heroType:
        path: /heroType/**
        sensitiveHeaders:
        url: http://localhost:8082/heroType
    hero:
        path: /hero/**
        sensitiveHeaders:
        url: http://localhost:8082/hero
    battleHero:
        path: /battleHero/**
        sensitiveHeaders:
        url: http://localhost:8081/battleHero
    formation:
        path: /formation/**
        sensitiveHeaders:
        url: http://localhost:8081/formation
    user:
        path: /user/**
        sensitiveHeaders:
        url: http://localhost:8085/user
    userResource:
        path: /userResource/**
        sensitiveHeaders:
        url: http://localhost:8085/userResource
    mail:
        path: /mail/**
        sensitiveHeaders:
        url: http://localhost:8084/mail
    battle:
        path: /battle/**
        sensitiveHeaders:
        url: http://localhost:8081/battle
    shop:
        path: /shop/**
        sensitiveHeaders:
        url: http://localhost:8086/shop
    chat:
        path: /chat/**
        sensitiveHeaders:
        url: http://localhost:8083/chat
    pvp:
        path: /pvp/**
        sensitiveHeaders:
        url: http://localhost:8085/pvp
    guild:
        path: /guild/**
        sensitiveHeaders:
        url: http://localhost:8087/guild
    guildMember:
        path: /guildMember/**
        sensitiveHeaders:
        url: http://localhost:8087/guildMember
    
#Spring Boot Config            
spring:
    profiles:
        active: default
    application:
        name: @pom.artifactId@